# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/customer_service_email_classification',
                'doc_host': 'https://cah-jake-bergren.github.io',
                'git_url': 'https://github.com/cah-jake-bergren/customer_service_email_classification',
                'lib_path': 'classifier'},
  'syms': { 'classifier.core': {'classifier.core.foo': ('schema.html#foo', 'classifier/core.py')},
            'classifier.schema': {'classifier.schema.load_emails': ('schema.html#load_emails', 'classifier/schema.py')}}}
