# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_evaluate.ipynb.

# %% auto 0
__all__ = ['display_evaluation_row']

# %% ../nbs/05_evaluate.ipynb 2
from pathlib import Path
from sklearn import metrics
import numpy as np
import pandas as pd

# %% ../nbs/05_evaluate.ipynb 8
def display_evaluation_row(idx: int, row: pd.Series) -> None:
    print("| -- IDX --|\n", idx)
    print("| -- RAW EMAIL -- |\n", row.email)
    print("| -- LABEL -- |\n", row.label)
    print("| -- PROMPT -- |\n", row.prompt)
    print("| -- PREDICTION -- |\n", row.prediction)
    print()
